server:
  port: 8300

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: tx
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://101.43.239.43:${server.port}/eureka/
