server:
  port: 8400
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          # 是否从注册中心读取服务
          enabled: true

eureka:
  instance:
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://101.43.239.43:8300/eureka/ #Eureka地址